2019-07-23 15:27:59,481 ERROR 31944 [-/127.0.0.1/-/1ms GET /] nodejs.ER_ACCESS_DENIED_ERRORError: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: NO)
    at Handshake.Sequence._packetToError (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Connection.js:525:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    --------------------
    at Protocol._enqueue (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Connection.js:119:18)
    at Pool.getConnection (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Pool.js:48:16)
    at /Users/mac/Desktop/blog-web/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/mac/Desktop/blog-web/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as getConnection] (/Users/mac/Desktop/blog-web/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at Pool.query (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Pool.js:202:8)
    at /Users/mac/Desktop/blog-web/node_modules/ali-rds/node_modules/pify/index.js:29:7
    sql: select now() as currentTime;
code: "ER_ACCESS_DENIED_ERROR"
errno: 1045
sqlMessage: "Access denied for user 'root'@'localhost' (using password: NO)"
sqlState: "28000"
fatal: true
name: "ER_ACCESS_DENIED_ERRORError"
pid: 31944
hostname: MacBook-Pro-3.local

2019-07-23 15:28:03,787 ERROR 31953 [-/127.0.0.1/-/1ms GET /] nodejs.ER_ACCESS_DENIED_ERRORError: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: NO)
    at Handshake.Sequence._packetToError (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Connection.js:525:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    --------------------
    at Protocol._enqueue (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Connection.js:119:18)
    at Pool.getConnection (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Pool.js:48:16)
    at /Users/mac/Desktop/blog-web/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/mac/Desktop/blog-web/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as getConnection] (/Users/mac/Desktop/blog-web/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at Pool.query (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Pool.js:202:8)
    at /Users/mac/Desktop/blog-web/node_modules/ali-rds/node_modules/pify/index.js:29:7
    sql: select now() as currentTime;
code: "ER_ACCESS_DENIED_ERROR"
errno: 1045
sqlMessage: "Access denied for user 'root'@'localhost' (using password: NO)"
sqlState: "28000"
fatal: true
name: "ER_ACCESS_DENIED_ERRORError"
pid: 31953
hostname: MacBook-Pro-3.local

2019-07-23 15:28:08,314 ERROR 31956 [-/127.0.0.1/-/1ms GET /] nodejs.ER_ACCESS_DENIED_ERRORError: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: NO)
    at Handshake.Sequence._packetToError (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Connection.js:525:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    --------------------
    at Protocol._enqueue (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Connection.js:119:18)
    at Pool.getConnection (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Pool.js:48:16)
    at /Users/mac/Desktop/blog-web/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/mac/Desktop/blog-web/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as getConnection] (/Users/mac/Desktop/blog-web/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at Pool.query (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Pool.js:202:8)
    at /Users/mac/Desktop/blog-web/node_modules/ali-rds/node_modules/pify/index.js:29:7
    sql: select now() as currentTime;
code: "ER_ACCESS_DENIED_ERROR"
errno: 1045
sqlMessage: "Access denied for user 'root'@'localhost' (using password: NO)"
sqlState: "28000"
fatal: true
name: "ER_ACCESS_DENIED_ERRORError"
pid: 31956
hostname: MacBook-Pro-3.local

2019-07-23 15:28:09,533 ERROR 31958 [-/127.0.0.1/-/0ms GET /] nodejs.ER_ACCESS_DENIED_ERRORError: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: NO)
    at Handshake.Sequence._packetToError (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Connection.js:525:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    --------------------
    at Protocol._enqueue (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Connection.js:119:18)
    at Pool.getConnection (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Pool.js:48:16)
    at /Users/mac/Desktop/blog-web/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/mac/Desktop/blog-web/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as getConnection] (/Users/mac/Desktop/blog-web/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at Pool.query (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Pool.js:202:8)
    at /Users/mac/Desktop/blog-web/node_modules/ali-rds/node_modules/pify/index.js:29:7
    sql: select now() as currentTime;
code: "ER_ACCESS_DENIED_ERROR"
errno: 1045
sqlMessage: "Access denied for user 'root'@'localhost' (using password: NO)"
sqlState: "28000"
fatal: true
name: "ER_ACCESS_DENIED_ERRORError"
pid: 31958
hostname: MacBook-Pro-3.local

2019-07-23 15:28:18,480 ERROR 31960 [-/127.0.0.1/-/0ms GET /] nodejs.ER_ACCESS_DENIED_ERRORError: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: NO)
    at Handshake.Sequence._packetToError (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Connection.js:525:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    --------------------
    at Protocol._enqueue (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Connection.js:119:18)
    at Pool.getConnection (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Pool.js:48:16)
    at /Users/mac/Desktop/blog-web/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/mac/Desktop/blog-web/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as getConnection] (/Users/mac/Desktop/blog-web/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at Pool.query (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Pool.js:202:8)
    at /Users/mac/Desktop/blog-web/node_modules/ali-rds/node_modules/pify/index.js:29:7
    sql: select now() as currentTime;
code: "ER_ACCESS_DENIED_ERROR"
errno: 1045
sqlMessage: "Access denied for user 'root'@'localhost' (using password: NO)"
sqlState: "28000"
fatal: true
name: "ER_ACCESS_DENIED_ERRORError"
pid: 31960
hostname: MacBook-Pro-3.local

2019-07-23 15:28:34,962 ERROR 31961 [-/127.0.0.1/-/1ms GET /] nodejs.ER_BAD_DB_ERRORError: ER_BAD_DB_ERROR: Unknown database 'operation_policy_clamp_00'
    at Handshake.Sequence._packetToError (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Connection.js:525:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    --------------------
    at Protocol._enqueue (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Connection.js:119:18)
    at Pool.getConnection (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Pool.js:48:16)
    at /Users/mac/Desktop/blog-web/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/mac/Desktop/blog-web/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as getConnection] (/Users/mac/Desktop/blog-web/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at Pool.query (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Pool.js:202:8)
    at /Users/mac/Desktop/blog-web/node_modules/ali-rds/node_modules/pify/index.js:29:7
    sql: select now() as currentTime;
code: "ER_BAD_DB_ERROR"
errno: 1049
sqlMessage: "Unknown database 'operation_policy_clamp_00'"
sqlState: "42000"
fatal: true
name: "ER_BAD_DB_ERRORError"
pid: 31961
hostname: MacBook-Pro-3.local

2019-07-23 15:28:36,370 ERROR 31963 [-/127.0.0.1/-/0ms GET /] nodejs.ER_BAD_DB_ERRORError: ER_BAD_DB_ERROR: Unknown database 'operation_policy_clamp_00'
    at Handshake.Sequence._packetToError (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Connection.js:525:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    --------------------
    at Protocol._enqueue (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Connection.js:119:18)
    at Pool.getConnection (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Pool.js:48:16)
    at /Users/mac/Desktop/blog-web/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/mac/Desktop/blog-web/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as getConnection] (/Users/mac/Desktop/blog-web/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at Pool.query (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Pool.js:202:8)
    at /Users/mac/Desktop/blog-web/node_modules/ali-rds/node_modules/pify/index.js:29:7
    sql: select now() as currentTime;
code: "ER_BAD_DB_ERROR"
errno: 1049
sqlMessage: "Unknown database 'operation_policy_clamp_00'"
sqlState: "42000"
fatal: true
name: "ER_BAD_DB_ERRORError"
pid: 31963
hostname: MacBook-Pro-3.local

2019-07-23 15:28:45,496 ERROR 31964 [-/127.0.0.1/-/0ms GET /] nodejs.ER_BAD_DB_ERRORError: ER_BAD_DB_ERROR: Unknown database 'blog-web'
    at Handshake.Sequence._packetToError (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Connection.js:525:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    --------------------
    at Protocol._enqueue (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Connection.js:119:18)
    at Pool.getConnection (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Pool.js:48:16)
    at /Users/mac/Desktop/blog-web/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/mac/Desktop/blog-web/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as getConnection] (/Users/mac/Desktop/blog-web/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at Pool.query (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Pool.js:202:8)
    at /Users/mac/Desktop/blog-web/node_modules/ali-rds/node_modules/pify/index.js:29:7
    sql: select now() as currentTime;
code: "ER_BAD_DB_ERROR"
errno: 1049
sqlMessage: "Unknown database 'blog-web'"
sqlState: "42000"
fatal: true
name: "ER_BAD_DB_ERRORError"
pid: 31964
hostname: MacBook-Pro-3.local

